ibpsa/project1-boptest

testcase/doc/README.md

Added README.md 

---

examples/szvav_sup.py
examples/twoday_p.py

Addresses https://github.com/ibpsa/project1-boptest/issues/45.

Issue45 kpi uni exa

---

.gitignore
README.md
examples/docker-compose.yml
examples/julia/Dockerfile
examples/julia/controllers.jl
examples/julia/szvav-sup.jl
examples/julia/twoday-p.jl

Julia-based controller implementation and a docker compose structure are added

add the julia-based controller examples

---

restapi.py

To address https://github.com/ibpsa/project1-boptest/issues/64

Issue64 Deactivate Flask debug mode

---

README.md
examples/julia/docker-compose.yml
examples/julia/makefile
testing/makefile

1. remove the docker compose yml file
2. update the unit test script
3. update the readme file

change the docker compose of julia docker into make file

---

testing/makefile
testing/utilities.py

Addresses https://github.com/ibpsa/project1-boptest/issues/70.

Make corrections.

---

parsing/SimpleRC.mo
parsing/parser.py
testcase1/models/SimpleRC.mo
testcase2/models/SingleZoneVAV.mo
testing/Dockerfile

Addresses the required change for updating to https://github.com/ibpsa/modelica-ibpsa/pull/1170/commits/9e1f57c6f859b8f25de7f21dc82333c5cbbb2677 as specified in https://github.com/ibpsa/project1-boptest/issues/49.

Issue49 signal exchange update

---

data/data_generator.py
testing/test_data.py

For https://github.com/ibpsa/project1-boptest/issues/98.

Issue98 occ num

---

testing/Dockerfile

This is for https://github.com/ibpsa/project1-boptest/issues/106

Update to Buildings master

---

Dockerfile
testing/Dockerfile
testing/test_testcase1.py

This is for https://github.com/ibpsa/project1-boptest/issues/105.

Update to Ubuntu18.

---

README.md

For https://github.com/ibpsa/project1-boptest/issues/110.

Add publications section

---

testcase2/models/SingleZoneVAV.mo

For https://github.com/ibpsa/project1-boptest/issues/119.

Update for latest Buildings master.

---

data/data_manager.py

For https://github.com/ibpsa/project1-boptest/issues/123.

Issue123 csv full year

---

data/data_generator.py

Addresses https://github.com/ibpsa/project1-boptest/issues/144.

Issue144 data gen args

---

testcase.py

For #154.
- Sets log level to 7 using updated pyfmi api.

issue154 set log level

---

forecast/forecaster.py

This is for https://github.com/ibpsa/project1-boptest/issues/165

Set default parameters from testcase in the forecaster if not provided

---

README.md
examples/python/twoday_p.py
testcases/testcase1/models/wrapped.mo
testcases/testcase2/models/wrapped.mo

For #168 
- Corrects customized kpi parameter reference
- Updates prototype testcase fmus so examples work
- Corrects readme to get examples to work

Issue168 err two day

---

data/data_generator.py

This is for https://github.com/ibpsa/project1-boptest/issues/174.

Add zone identifier as argument for methods of data generator

---

kpis/kpi_calculator.py

This is for https://github.com/ibpsa/project1-boptest/issues/176.

Issue176 Change source references to use names instead of indexes

---

examples/python/szvav_sup.py
examples/python/twoday_p.py
restapi.py
testcase.py

This modification allows users to specify
1.  the start time 
2.  the warmup period length

modified the reset function 

---

testcases/testcase3/models/TwoZones.mo
testing/test_testcase3.py

To address https://github.com/ibpsa/project1-boptest/issues/181.

Issue181 change testcase3 offset 

---

data/data_manager.py
kpis/kpi_calculator.py

This is for https://github.com/ibpsa/project1-boptest/issues/179.

Issue179 data manager check

---

testcases/testcase1/models/set_library_versions.sh
testcases/testcase2/models/set_library_versions.sh
testcases/testcase3/models/set_library_versions.sh
testing/Dockerfile

Issue202 modelicapath

---

parsing/parser.py

This is for https://github.com/ibpsa/project1-boptest/issues/146

Issue146b python3

---

testing/makefile

For https://github.com/ibpsa/project1-boptest/issues/220.

Issue220 Add test_bestest_hydronic to test_all

---

boptest_client/boptest_client.py

This PR adds more methods to the BoptestClient which makes the access to BOPTEST more method based instead of requests/string-based.
@kbenne -- can you please provide your opinion on this?

add more methods to boptest client api

---

README.md
testing/makefile

Issue294 remove gecko

---

README.md

Patch for issue 318

---

docs/DesReqGui/source/core_kpi.rst
kpis/kpi_calculator.py
license.md
testcase.py
testing/test_testcase1.py

This is for #327.
@JavierArroyoBastida After you review, I'll update reference results.  Please also let me know if it is worth keeping the plot functionality of ``kpi_calculator.get_computational_time_ratio()``, as it would need to be fixed to use a vector of stored simulation steps, rather than assuming constant throughout the test period.

Issue327 com tim rat

---

testing/Dockerfile

Add Complex.mo to MODELICAPATH

---

contributors.md

@valgavan and @haraldwalnum I'd like to add you to the list in the ``contributors.md`` file.  Let me know if this is ok.

Add new contributors

---

README.md

This is to add the recently published journal article to the readme.  I suggest also in https://github.com/ibpsa/project1-boptest/issues/378 to add other related publications.

Patch - add journal 2021

---

README.md

This adds related publications to README.md.

issue378 add pubs

---

examples/javascript/Dockerfile
examples/javascript/makefile

Issue 389 javascript example

---

README.md

Adds a publication link in Readme

patch - Add publication link

---

parsing/parser.py
releasenotes.md

Fix issue using parser with python3

---

testcases/multizone_office_simple_air/doc/index.html
testcases/multizone_office_simple_air/models/MultiZoneOfficeSimpleAir/TestCases/TestCase.mo

This is for #414 and edits docs only.

Issue 414 Fix Docs for Multizone Office Simple Air

---

.travis.yml
examples/python/testcase1.py
examples/python/testcase1_scenario.py
examples/python/testcase2.py
examples/python/testcase3.py
releasenotes.md

Issue 416 unit tests failing

---

README.md
releasenotes.md

Issue 419 Setting Test Case in Windows

---

releasenotes.md

Just forgot to update release notes in #454 for #450.

Release notes update

---

README.md
contributors.md
releasenotes.md
testcases/README.md

Issue451 readme update

---

releasenotes.md
testing/test_bestest_air.py
testing/test_bestest_hydronic.py
testing/test_bestest_hydronic_heat_pump.py
testing/test_multizone_office_simple_air.py
testing/test_multizone_residential_hydronic.py
testing/test_singlezone_commercial_hydronic.py
testing/test_testcase1.py
testing/test_testcase2.py
testing/test_testcase3.py
testing/utilities.py

Issue463 abstract test case tests

---

docs/tutorials/CCAISummerSchool2022/README.md

For https://github.com/ibpsa/project1-boptest/issues/433.

Issue433 ccai2022 tutorial

---

data/get_html_IO.py
releasenotes.md

This pull request is for issue #487.

Updated get_html_IO.py to latest API

---

data/get_html_IO.py
releasenotes.md

Issue487 update gethtml io

---

README.md

This is a patch for readme typos.

Patch to fix readme typos

---

license.md

Update copyright year

---

releasenotes.md
testcase.py

Issue554 forecast horizons of 0

---

releasenotes.md
testcase.py

This is for #554 following PR #558 to see if it triggers the Branch CI.
FYI @JavierArroyoBastida

Issue554 forecast horizon0

---

README.md

Improve user-experience and makes it easy to follow README.
Note: Referencing https://github.com/ibpsa/project1-boptest/issues/537

Added instructions in README to add to PYTHONPATH

---

docs/08_contributors.md
docs/_data/testcases_menubar.yml
docs/testcases_ibpsa_multizone_office_simple_hydronic.md

ghPages add multizone_office_simple_hydronic

---

releasenotes.md
testcase.py
testing/test_bestest_air.py

This is for #546.  It:
- implements test to check for problem
- implements fix
- updates release notes

Issue546 sce flag

---

README.md
examples/python/testcase1.py
examples/python/testcase2.py
examples/python/testcase3.py

Based on issue #565, a commit has been made.

fix issue #565

---

README.md
examples/python/testcase1.py
examples/python/testcase2.py
examples/python/testcase3.py
releasenotes.md

This is for #565 and is extension of https://github.com/ibpsa/project1-boptest/pull/574.

Issue565 patch pythonpath

---

releasenotes.md

Patch - Update releasenotes.md

---

examples/javascript/Dockerfile
examples/javascript/makefile

@dhblum could you please take a look at it?

issue594_javascript_update

---

releasenotes.md

Issue594 javascript update

---

releasenotes.md

Update origin branch with local fork

Updated release notes

---

Dockerfile
releasenotes.md

This is for #643 and updates pyfmi and miniconda versions.  Still to do:

Update conda and pyfmi versions

---

contributors.md
web/08_contributors.md
web/Dockerfile
web/ibpsa_project_participation.md
web/ibpsa_project_workplan.md

@dhblum I'm updating my affiliation in the website since it was not used consistently.

Update Javier's affiliation.

---

docs/design/source/testcasedev.rst

This is to update the test case requirements summary in the design specification to current requirements.

Patch - Update test case requirements summary

---

contributors.md

Fix Javier's affiliation from KU Leuven to Wedoco.

Patch - Update Contributors

---

releasenotes.md
testcases/bestest_hydronic_heat_pump/doc/index.html
testcases/bestest_hydronic_heat_pump/models/BESTESTHydronicHeatPump/TestCase.mo

This is for #704 
1) Added correct documentation of HP to BESTEST hydronic heat pump testcase. Added in .mo file and index.html in docs.
2) Automatic whitespace removals by pre-commit hooks

Issue704 Add heat pump documentation for bestest hydronic HP testcase

---

bacnet/create_ttl.py
releasenotes.md
testcases/multizone_office_simple_hydronic/models/bacnet.ttl

This is for #735, by adding the appropriate ``bacnet.ttl`` file to ``multizone_hydronic_simple_hydronic``.

Issue735 new bacttl

---

releasenotes.md
testcase.py
testcases/bestest_air/models/config.json
testcases/bestest_hydronic/models/config.json
testcases/bestest_hydronic_heat_pump/models/config.json
testcases/multizone_office_simple_air/models/config.json
testcases/multizone_office_simple_hydronic/models/config.json
testcases/multizone_residential_hydronic/models/config.json
testcases/singlezone_commercial_hydronic/models/config.json
testcases/testcase1/models/config.json
testcases/testcase2/models/config.json
testcases/testcase3/models/config.json
testcases/twozone_apartment_hydronic/models/config.json

This is for #719, by removing the ``scenario`` field from the test case ``config.json``.

issue719 scenario field

---

bacnet/BopTestProxy.py
bacnet/create_ttl.py
contributors.md
releasenotes.md
testcases/bestest_air/models/bacnet.ttl
testcases/bestest_hydronic/models/bacnet.ttl
testcases/bestest_hydronic_heat_pump/models/bacnet.ttl
testcases/multizone_office_simple_air/models/bacnet.ttl
testcases/multizone_office_simple_hydronic/models/bacnet.ttl
testcases/multizone_residential_hydronic/models/bacnet.ttl
testcases/singlezone_commercial_hydronic/models/bacnet.ttl
testcases/twozone_apartment_hydronic/models/bacnet.ttl

This is for #762 and follows from PR https://github.com/ibpsa/project1-boptest/pull/752.

Issue762 status flags

---

.travis.yml
releasenotes.md

This is for #787.  
First trying to remove custom docker installation.

Issue 787 Docker Unit Tests
