ibpsa/project1-boptest

testing/Dockerfile

Uses ibpsa-modelica master since signal exchange block was merged in https://github.com/ibpsa/modelica-ibpsa/pull/1170.

Change to ibpsa modelica master.

---

README.md

This changes the icon to the .com domain of travis as the CI tests have been migrated.

Changed from travis-ci.org to travis-ci.com

---

docs/DesReqGui/source/testcasedev.rst

This is for #204 
- Adds a note to the test case development requirements documentation that unnecessary columns can be omitted.

Add note to doc 204

---

.gitignore
testcases/bestest_hydronic_heat_pump/models/Resources/calibration/calibration.py

This PR does the following:
* Add a couple entries to the .gitignore
* The `calibration.py` file had a couple `10. * xyz` lines. Autopep converts this to `1 0. *`, which causes issues. This change does not impact the code, just updates the style.

Update gitignore and fix autoformat of calibration

---

restapi.py
testcase.py

This is for #258.  Namely, it:
- Changes ``testcase.u_store`` and ``testcase.y_store`` to use numpy arrays instead of python lists.
- Edits ``restapi.Results`` to convert numpy arrays to lists for transfer over http, since numpy arrays are not json serializable

Store data as numpy arrays

---

.travis.yml
testing/makefile

This is for #450.  In particular, it splits each test into parallel jobs so as to avoid the travis job timeout error.  This replaces #452 and #453.

Issue450 split travis jobs

---

README.md
contributors.md
testcases/README.md

Instructions for building and deploying a test case -- which say to define the `TESTCASE` env var as a directory rather than the testcase name -- currently fail:
```
$ TESTCASE=./testcases/testcase1/ docker-compose up
[+] Running 1/1
⠿ Container project1-boptest-boptest-1  Recreated                                             0.2s
Attaching to project1-boptest-boptest-1
project1-boptest-boptest-1  | Traceback (most recent call last):
project1-boptest-boptest-1  |   File "restapi.py", line 63, in <module>
project1-boptest-boptest-1  |     case = TestCase()
project1-boptest-boptest-1  |   File "/home/developer/testcase.py", line 49, in __init__
project1-boptest-boptest-1  |     self.data_manager.load_data_and_jsons()
project1-boptest-boptest-1  |   File …
```

Update README so building and deploying test case doesn't fail

---

releasenotes.md
testing/makefile

This is to close #466.  It adds a command to run ``testing/report.py`` to all individual tests in the ``testing/makefile``.  I think this is all that should be needed, and seems to work locally on reporting success and failures.

Issue 466 Unit Test Reporting

---

testing/makefile

This is for #504 and does not change travis unit tests or affect BOPTEST functionality.

Correct typo in test_all

---

releasenotes.md
testing/test_bestest_air.py
testing/test_bestest_hydronic.py
testing/test_bestest_hydronic_heat_pump.py
testing/test_multizone_office_simple_air.py
testing/test_multizone_residential_hydronic.py
testing/test_singlezone_commercial_hydronic.py
testing/test_testcase1.py
testing/test_testcase2.py
testing/test_testcase3.py
testing/test_twozone_apartment_hydronic.py
testing/utilities.py

This is for #529.  It specifies a specific forecast point to check for each test case in associated unit test.

Issue529 che for lis ord

---

kpis/kpi_calculator.py
releasenotes.md

The issue #540 reports an invalid JSON format when a KPI indicator is requested at the beginning of a scenario. This occurs because the kpi_calculator.get_computational_time_ratio function returns an np.nan value when no time ratio is available. Since the Flask JSON encoder cannot convert np.nan to null, this results in an incorrect JSON format.
I propose to return an arbitrary zero value from get_computational_time_ratio if no data is available for computation. This fixes issue #540 with a very minor change.

fix issue #540

---

contributors.md
kpis/kpi_calculator.py
releasenotes.md

This is for #540.  In particular, it fixes the KPI calculator so that it returns a Python None object for the computational time ratio KPI instead of NaN if the test has not been advanced yet.
Verified using Mozilla Firefox browser for testcase2 after starting test case but not advancing at all, as exampled in #540 to demonstrate error:
Unit tests should pass.
@Enderdead can you verify I updated ``contributors.md`` properly for you?  And thank you for the fix.

Issue540 nan kpi

---

examples/javascript/Dockerfile
examples/javascript/makefile
releasenotes.md

This is for #594.  See if works on travis.  It works locally.
@SenHuang19 Can you also just add a note to the ``releasenotes.md`` for this (in the backwards compatible section)?

Issue594 javascript update

---

Dockerfile
contributors.md
releasenotes.md

Pin the base Docker image to `linux/x86_64` to enable the image to be used on Apple Silicon machines easily. This can be reverted when PyFMI is distributed to `linux/arm64` (https://github.com/modelon-community/PyFMI/issues/212).
Error for future reference:
```
$ docker-compose up
...
1.589 2024-01-22 16:51:21 (54.1 MB/s) - '/home/user/miniconda.sh' saved [74403966/74403966]
1.589
1.600 PREFIX=/home/user/miniconda
1.816 Unpacking payload ...
1.822 rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
1.822  /home/user/miniconda.sh: line 352:    38 Exit 141                extract_range $boundary1 $boundary2
1.822         39 Trace/breakpoint trap   | "$CONDA_EXEC" constructor --extract-tarball --prefix "$PREFIX"
------
failed to solve: process "/bin/sh -c cd $HOME && \twget …
```

Pin Dockerfile image to `linux/x86_64`

---

docs/design/source/testcasedev.rst
releasenotes.md
testing/utilities.py

This is for #601.  Corrects typos in design docs.

Issue601 typo des doc

---

releasenotes.md
testing/Dockerfile

This addition allows me to compile a Modelica + Spawn of EnergyPlus emulator without issues. Otherwise, there are EnergyPlus related linker errors due to a file that is unlikely to be correct on the filesystem:
```
/usr/bin/ld:/home/developer/git/modelica-buildings/Buildings/Resources/Library/linux64/[libModelicaBuildingsEnergyPlus.so](http://libmodelicabuildingsenergyplus.so/): file format not recognized; treating as linker script
```
Fixes https://github.com/ibpsa/project1-boptest/issues/613.

Install and initialize Git LFS in `testing/Dockerfile`

---

releasenotes.md
testcases/multizone_office_simple_air/doc/index.html
testcases/multizone_office_simple_air/models/MultiZoneOfficeSimpleAir/TestCases/TestCase.mo

This PR is to address issue #605, where is shown that a typo is present in the documentation for the cooling setpoint in unoccupied period. After verifying that it is indeed a just a typo, I updated the documentation.

Corrected typo in documentation for multizone_office_simple_air

---

releasenotes.md
testcase.py

@dhblum. Here is a first version of implementation of automatic storing results.
Please comment, both on the implementation and which parameters should be stored in results.json

Issue626 store results

---

.travis.yml
releasenotes.md
testing/makefile

This is for #634.  It drops support of testing example controllers with Python 2.

Issue634 python2 examples

---

data/data_manager.py
releasenotes.md

This PR addresses #500, a warning was added to the `data/data_manager.py` script if any of the weather variables present in `data/categories.json` is missing from `wrapped.fum/resources/weather.csv`.

Issue500 update data manager

---

.travis.yml
Dockerfile
releasenotes.md
testing/utilities.py

This is for https://github.com/ibpsa/project1-boptest/issues/655 and https://github.com/ibpsa/project1-boptest/issues/657:
-  moves matplotlib import to the one necessary function, which is only used locally and not in travis ci.
- removes installation of matplotlib in travis.
- specifies version of scipy to 1.13.0 in test case Dockerfile.
Ready to merge if tests pass.

Issue655 numpy matplotlib

---

testcases/multizone_office_simple_hydronic/doc/index.html
testcases/multizone_office_simple_hydronic/models/BuildingEmulators/BuildingSystem.mo

This is for #677.  It fixes a typo in documentation for multizone_office_simple_hydronic.

issue677 Fix Doc Typo

---

license.md
releasenotes.md
testcases/bestest_hydronic/models/BESTESTHydronic/TestCase.mo
testcases/bestest_hydronic/models/BESTESTHydronic/package.mo
testcases/bestest_hydronic_heat_pump/models/BESTESTHydronicHeatPump/TestCase.mo
testcases/bestest_hydronic_heat_pump/models/BESTESTHydronicHeatPump/package.mo

This pull request is for #680. Modelica code of `BETEST_hydronic` and `BESTEST_hydronic_heat_pump` was updated to NOT extend from model of IDEAS library, but instead duplicate it, to make test case Modelica code maintenance easier.

Issue680 update dependency bestest hydronic

---

.github/workflows/build_test_containers.yml
service/ci/publish_to_docker.sh
service/ci/publish_to_github.sh

For #712 in place of https://github.com/ibpsa/project1-boptest/pull/723.

Issue712 service deployment 2

---

docs/design/source/conf.py
docs/design/source/forecasts.rst

The users guide in /docs/design/source/forecasts.rst is updated with a description of uncertainty emulator model development and integration into BOPTEST.

Docs and guide updated for wetaher forecast uncertainty emulator.

---

docker-compose.yml
releasenotes.md

This is for #769 and tags the versions of docker images for ``minio/minio`` and ``minio/mc``.

Issue769 patch minio tag

---

README.md

This is a quick patch to the readme to fix the travis build status icon.

Patch - Fix readme travis build status icon
